### ISSUE TITLE
Add support for unsharing user namespaces

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#1043]
Right now we have no support for unsharing user namespaces in the pause implementation:

https://github.com/containers/conmon-rs/blob/2e123a1c8be05d84f5141a7319566e55d4e5b2e0/conmon-rs/server/src/pause.rs#L104-L108

https://github.com/containers/conmon-rs/blob/2e123a1c8be05d84f5141a7319566e55d4e5b2e0/conmon-rs/server/src/pause.rs#L168-L172

https://github.com/containers/conmon-rs/blob/2e123a1c8be05d84f5141a7319566e55d4e5b2e0/pkg/client/client_test.go#L548

We should implement it before releasing 0.5.0.

**Comment by saschagrunert** [comment]
I can start working on this next week if nobody else want to.

**Comment by haircommander** [comment]
it's all yours :)
