### ISSUE TITLE
PAUSE_PATH should be configurable

### ISSUE THREAD

**Issue by haircommander** [containers/conmon-rs#1065]
As CNI plugins require the namespaces are viewable under `/var/run/netns` 
In pinns, the parent directory was passed `/var/run` and then pinns created sub-directories for each namespace type based on name. we could do something similar

**Comment by haircommander** [comment]
sorry I didn't catch this in reviews @saschagrunert . I have one more too I'll be submitting. I can take either if you're too busy

**Comment by saschagrunert** [comment]
Working on it as part of https://github.com/containers/conmon-rs/pull/1067
