### ISSUE TITLE
[rhcontainerbot/podman-next copr] conmon-rs builds have the same release tag

### ISSUE THREAD

**Issue by lsm5** [containers/conmon-rs#1173]
### What happened?

Ever since the switch to packit for post-commit copr builds on `rhcontainerbot/podman-next` all builds of conmon-rs have the exact same NVR.

See `Package Version` in https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/package/conmon-rs/

### What did you expect to happen?

The build release tags should be different for every build.

### How can we reproduce it (as minimally and precisely as possible)?

See the copr link. `conmon-rs.spec.rpkg` has `Release: 1%{?dist}` which gets used as-is in the post-commit build. The release tag needs to be updated somehow during the build process.

### conmon-rs version

NA

### OS version

NA

### Additional environment details (AWS, VirtualBox, physical, etc.)

fedora copr.

**Comment by lsm5** [comment]
wonder if we can reuse `.packit.sh` in post-commit builds which will update release tag with `$PACKIT_RPMSPEC_RELEASE`

**Comment by saschagrunert** [comment]
Awesome, thank you for digging into this @lsm5!

**Comment by lsm5** [comment]
whoops nope, issue was .packit.sh had a wrong sed for the release tag. My bad. Fixing it now..
