### ISSUE TITLE
Update rust version

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#1231]
@rphillips @haircommander @lsm5 I'd like to bump the rust version because many dependencies are not upgradeable right now: https://deps.rs/repo/github/containers/conmon-rs

Do we already know if RHEL8 is the only blocker with 1.58? I assume we could not switch to RHEL9 exclusively, right?

RHEL9 / UBI9 seems to ship at least:
```
rustc 1.62.1 (Red Hat 1.62.1-1.el9)
```

**Comment by haircommander** [comment]
> I assume we could not switch to RHEL9 exclusively, right?

this is an interesting idea. We could consider only supporting newer rustc versions and only have support downstream when a new enough version is available

**Comment by lsm5** [comment]
centos 8 stream is now on rust 1.66.1. So I think we should be ok. Did you see 1.58 recently on rhel 8 ?
