### ISSUE TITLE
`main` branch builds on epel 8/9 failing

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#1254]
Looks like we still have no Rust 1.66 in there:
```
error: package `anstyle v0.3.5` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.62.1
```

* https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/epel-8-x86_64/05742276-conmon-rs/builder-live.log.gz
* https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/epel-9-x86_64/05742276-conmon-rs/builder-live.log.gz

@lsm5 do you have any idea how we can bump the versions there?

**Comment by lsm5** [comment]
let's see if this works: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/5745252/ (building)

**Comment by lsm5** [comment]
for whatever reason, copr builds can't seem to find gitlab.com. I'll give this a try later.

**Comment by saschagrunert** [comment]
Thank you @lsm5! :pray:

**Comment by lsm5** [comment]
It's kinda hard to know who's actually using those repos, so there might be quite a few angry people once I actually disable those repos :fearful:

**Comment by lsm5** [comment]
> I'm thinking I should just remove the epel-* branches. rustc is frequently out of date, also causes failures on netavark and aardvark-dns.
> 
> People who have the copr enabled on their rhel envs will need to re-add the centos-stream+epel-next-* repos.

@saschagrunert wdyt ?

**Comment by saschagrunert** [comment]
Sounds good to me, thank you!
