### ISSUE TITLE
Update capnproto to v0.19.0

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#1688]
The package update contains breaking changes as outlined in the blog:

https://github.com/capnproto/capnproto-rust/blob/82aa8a2163b5eadaa83aa2716ce781fc78107c2c/blog/_posts/2023-09-04-0.18-release.md

We should bump all dependencies to v0.18.0 and manually migrate the code.

**Comment by shanipribadi** [comment]
0.19.0 is coming out with another minor breaking changes.

https://github.com/capnproto/capnproto-rust/blob/6dbd38ea1290b0ceeb90258fdf9536a050f384ec/blog/_posts/2024-01-14-0.19-release.md

should this issue be updated to updating to v0.19.0 directly?

**Comment by saschagrunert** [comment]
@shanipribadi yes, I updated the issue. Do you want to give the update a try?
