### ISSUE TITLE
Memory usage after first tonic request

### ISSUE THREAD

**Issue by rphillips** [containers/conmon-rs#19]
I was adding a RPC request to return RSS memory and noticed the RSS usage goes up in the server after the first GRPC request... significantly.

Terminal 1:
```
# target/release/conmon-server --runtime /bin/ls
```

Terminal 2:
```
# cat /proc/$(pidof conmon-server)/status|grep RSS
VmRSS:      1084 kB
# target/release/conmon-client
Version: Response { metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Wed, 10 Nov 2021 21:55:01 GMT", "grpc-status": "0"} }, message: VersionResponse { version: "0.1.0" }, extensions: Extensions }
# cat /proc/$(pidof conmon-server)/status|grep RSS
VmRSS:      3464 kB
```

**Comment by saschagrunert** [comment]
@rphillips that's the reason why we have the mismatch between CI and our local tests. We test that the binary is up and running by verifying that the client works. Great find!

**Comment by rphillips** [comment]
I'm still seeing this issue with #20.

**Comment by saschagrunert** [comment]
> I'm still seeing this issue with #20.

I'm not on my local machine but I can reproduce in https://github.com/containers/conmon-rs/pull/22

**Comment by rphillips** [comment]
In #27 we migrated to capnproto
