### ISSUE TITLE
Catch container OOM

### ISSUE THREAD

**Issue by haircommander** [containers/conmon-rs#297]
the current implementation of conmon listens to the container's `cgroup.events` file to check whether a container OOMed after it died. We should do a similar thing in conmonrs

**Comment by rphillips** [comment]
The [conmon OOM detection code](https://github.com/containers/conmon/blob/283294c3d7bac12cbc977c1e3217932edab139e5/src/cgroup.c#L30-L31) has support for cgroup v1 and cgroup v2.
