### ISSUE TITLE
use mio or other event based io for stream

### ISSUE THREAD

**Issue by haircommander** [containers/conmon-rs#299]
currently, there's a bug where running with multiple exec sync or containers causes conmonrs to leak threads. This is from the streams::read_loop_single_stream `reader.read` call. we're doing a normal blocking read, and waiting on I/O that will never come (nor be canceled). 

We need to either not block on the IO, use an event based system, or be able to cancel the read when we know there are no more messages

**Comment by cgwalters** [comment]
Any reason not to use async/tokio for that?  An async read scheduled via Tokio should just be registering the fd to epoll, and dropping the future should unregister.

**Comment by saschagrunert** [comment]
> Any reason not to use async/tokio for that? An async read scheduled via Tokio should just be registering the fd to epoll, and dropping the future should unregister.

When would we know when to drop the future? 

> be able to cancel the read when we know there are no more messages

Same question would apply to this.

Maybe the `stop_tx` should be part of the spawned thread… :thinking: 

https://github.com/containers/conmon-rs/blob/a05320d90b396fe6e121e18db5b8a0a72f05573b/conmon-rs/server/src/streams.rs#L100-L118
