### ISSUE TITLE
Choose RPC framework

### ISSUE THREAD

**Issue by haircommander** [containers/conmon-rs#3]
there are tons of RPC frameworks to choose from. we've flirted with the idea of grpc, ttrpc, [cap n proto](https://github.com/capnproto/capnproto-rust). we should probably just pick one. any other ideas?

**Comment by saschagrunert** [comment]
I think tonic via unix domain sockets and golang GRPC is still broken due to https://github.com/hyperium/h2/pull/487, but we have to give it a try.

**Comment by mrunalp** [comment]
One worry I have is about the binary size and the memory usage. I opened a PR https://github.com/containers/conmon-rs/pull/4 to set some flags during build time. I think if we stay under < 4MB RSS that may be okay if we run one conmon for a pod.

**Comment by rphillips** [comment]
I took a look at the server and see it using 3.0 MB RSS in release mode. Removing Tonic decreases RSS to 1 MB (still using tokio). Perhaps it does make sense to find something lighter weight.

**Comment by saschagrunert** [comment]
I was able to trim-down the RSS by testing cap'n proto: https://github.com/containers/conmon-rs/pull/8

**Comment by saschagrunert** [comment]
I think we can close this one now and stick with tonic. I'll add a CI job to compare the used RSS of PRs.
