### ISSUE TITLE
attach metadata to logger

### ISSUE THREAD

**Issue by haircommander** [containers/conmon-rs#369]
the rust logger allows us to attach metadata. it would be useful to track different messages based on container id, or pid if that's not possible, so we know which container did what

**Comment by saschagrunert** [comment]
Are you thinking to use something like slog: https://docs.rs/slog/latest/slog/?

**Comment by haircommander** [comment]
yeah that looks cool, though would that mean we need to store a logger per container to sneak in the container ID per request. I'm not sure what the overhead of that would be. I a;so may be interpreting the docs wrong

**Comment by saschagrunert** [comment]
Hm looks like that https://docs.rs/tracing/latest/tracing is the new de-facto standard.
