### ISSUE TITLE
gettext-sys compile times

### ISSUE THREAD

**Issue by rphillips** [containers/conmon-rs#43]
Is there a way to get rid of gettext-sys? We use it for setting the locale, but the compile times with it seem to be quite long.

**Comment by haircommander** [comment]
maybe https://docs.rs/locale/0.2.2/locale/linux/ffi/index.html?

**Comment by haircommander** [comment]
or we could probably call directly in libc https://rust-lang.github.io/hashbrown/libc/fn.setlocale.html

**Comment by saschagrunert** [comment]
Yeah I noticed this as well, especially with rust-analyzer it recompiles the whole gettext lib every time. Using the libc function should be fine, right?

**Comment by rphillips** [comment]
Created a fix https://github.com/containers/conmon-rs/pull/53
