### ISSUE TITLE
Add support for OpenTelemetry tracing

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#481]
We're already using the tracing crate, which has support for Open Telemetry (OTEL) as well: https://github.com/tokio-rs/tracing/tree/master/tracing-opentelemetry

Using the crate would probably incorporate adding those, too:
- https://docs.rs/opentelemetry
- https://docs.rs/opentelemetry-jaeger

Independently how we wanna use it from a configuration perspective, having OTEL support would increase the observability of the runtime stack (together with CRI-O) by gaining much more insights about what is going on in conmon-rs.

**Comment by doehyunbaek** [comment]
This seems very interesting. If you don't mind I want to tackle this issue.

Quick [search](https://github.com/containers/conmon-rs/search?q=debug_span) into repo with keyword 'debug_span' revealed 6 files currently being traced. Is this issue about turning those tracing points into OTEL compatible tracepoints?

**Comment by doehyunbaek** [comment]
Thanks for reply. Really appreciate it.

Unfortunately, I think I would be occupied with day job / IRL minimum 2 weeks, I would like to tackle it after that. Would that be ok? If anyone tries to take this issue in the meantime I would not mind him taking the issue.

**Comment by saschagrunert** [comment]
@doehyunbaek yep that's totally fine, no need to rush on this topic! :+1:

**Comment by saschagrunert** [comment]
@doehyunbaek do you still have interest in working on it? Just wanted to check-in if priorities have been changed.

**Comment by doehyunbaek** [comment]
Hi. I quit my previous job in the meantime and am planning on switching to other fields which do not involve container technologies :(. I do not have interest in working on it. Sorry for late reply.

**Comment by jakecorrenti** [comment]
I can give this a shot. I can pick at it here and there, but can really sit down and work on it next week when my internship ends (assuming I don't get it done before then).

**Comment by jakecorrenti** [comment]
Hi, I just started working on this issue, and I wanted to try and run the tests to see if that would provide any data on the Jaeger dashboard. However, I keep getting this error when I try to do `make integration`, and I can't seem to nail down what could be going wrong here. 
```
exec: "go": executable file not found in $PATH
```

``` 
$ echo $PATH
/usr/local/opt/gnu-getopt/bin:/usr/local/opt/gnu-getopt/bin:/home/jakecorrenti/.cargo/bin:/home/jakecorrenti/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin
```

**Comment by haircommander** [comment]
`make integration` runs the tests with `sudo`, what is `sudo echo $PATH`? I 'm guessing it's missing /usr/local/go/bin

**Comment by jakecorrenti** [comment]
This appears to be fine as well 
```
$ sudo echo $PATH
/usr/local/opt/gnu-getopt/bin:/home/jakecorrenti/.cargo/bin:/home/jakecorrenti/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/usr/local/go/bin
```

**Comment by haircommander** [comment]
what about `sudo -E echo $PATH`?

**Comment by jakecorrenti** [comment]
I figured it out, I needed to add `/usr/local/go/bin` to `/etc/sudoers`
