### ISSUE TITLE
RPM Packaging

### ISSUE THREAD

**Issue by rphillips** [containers/conmon-rs#578]
### What happened?

I received some tips for packaging conmon-rs RPMs from @cgwalters. Generally [bootupd](https://github.com/coreos/bootupd) looks like a good example. The bootupd github releases contain a source tar and a vendor tar. The [bootupd.spec](https://src.fedoraproject.org/rpms/rust-bootupd/blob/rawhide/f/rust-bootupd.spec) uses both tarballs to generate the resulting rpm.

Starting points could be:

- [x] On conmon-rs tag, create a release with a vendor tarball and a source tarball using a GH action 

### What did you expect to happen?

None

### How can we reproduce it (as minimally and precisely as possible)?

None

### conmon-rs version

NONE
<details>

```console
$ conmonrs --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by saschagrunert** [comment]
Sounds good, would it make sense for us to generate the RPM for every commit?

**Comment by rphillips** [comment]
The RPM generation can be done on https://src.fedoraproject.org/ or other build servers... I don't think we actually have to build the RPMs in this repo.

**Comment by rphillips** [comment]
Tagged releases now upload the vendor and source payloads.

**Comment by rphillips** [comment]
@lsm5 also added a copr build https://github.com/containers/conmon-rs/pull/602

I added a spec on pagure here https://pagure.io/conmon-rs to use the Releases.
