### ISSUE TITLE
Centos and epel packages fail to build on COPR

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#675]
### Which jobs are failing?

The recent builds fail on each `main` commit: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4788630/

### Which tests are failing?

Every copr build on `main`

### Since when has it been failing?

I don't think they ever worked.

cc @rphillips @lsm5

**Comment by lsm5** [comment]
I removed the dependency on external copr `lsm5/wasmtime` and added wasmtime into the podman-next copr itself.

Latest build at: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4803413/

c9s and c8s are successful.

epel 9 uses cargo: `cargo-1.58.1-1.el9` and currently it's failing with:
```
cargo build --release
    Updating crates.io index
error: failed to select a version for the requirement `tzdb = "^0.4.4"`
candidate versions found which didn't match: 0.3.6, 0.3.5, 0.3.4, ...
location searched: crates.io index
required by package `shadow-rs v0.16.3`
    ... which satisfies dependency `shadow-rs = "^0.16.3"` (locked to 0.16.3) of package `conmonrs v0.1.0 (/builddir/build/BUILD/conmon-rs/conmon-rs/server)`
make: *** [Makefile:18: release] Error 101
error: Bad exit status from /var/tmp/rpm-tmp.4cFbMb (%build)
    Bad exit status from /var/tmp/rpm-tmp.4cFbMb (%build)
```

Similar for epel-8: `cargo-1.58.1-1.module+el8.6.0+14021+586eff1a`
```
cargo build --release
    Updating crates.io index


RPM build errors:
error: failed to select a version for the requirement `tzdb = "^0.4.4"`
candidate versions found which didn't match: 0.3.6, 0.3.5, 0.3.4, ...
location searched: crates.io index
required by package `shadow-rs v0.16.3`
    ... which satisfies dependency `shadow-rs = "^0.16.3"` (locked to 0.16.3) of package `conmonrs v0.1.0 (/builddir/build/BUILD/conmon-rs/conmon-rs/server)`
make: *** [Makefile:18: release] Error 101
error: Bad exit status from /var/tmp/rpm-tmp.CyesTZ (%build)
    Bad exit status from /var/tmp/rpm-tmp.CyesTZ (%build)
```

@saschagrunert @haircommander @rphillips If we're happy with c9s and c8s, I could just disable the epel builds, let me know.

**Comment by saschagrunert** [comment]
@lsm5 thank you! I assume that we need the epel builds for RHCOS later on, so I guess we have to fix the build on our end.

**Comment by lsm5** [comment]
@saschagrunert so c8s uses cargo v1.60 which is the least version (AFAICT) for a successful build, while epel8 and epel9 are currently 1.58. Possible options are:

1. Make conmon-rs work with cargo 1.58
2. Wait for epel buildroot to get cargo 1.60 (I gotta check ETA )
3. Do some gymnastics for epel repos to use cargo from stream repos.

I think 1 would be ideal if doable, but if not, I can check on 2 and 3.

**Comment by saschagrunert** [comment]
> * Make conmon-rs work with cargo 1.58

I played around with 1.58 and we could disable the tzdb feature, but this leads into a new issue:
```
error: package `time v0.3.14` cannot be built because it requires rustc 1.59.0 or newer, while the currently active rustc version is 1.58.1
```

**Comment by lsm5** [comment]
> > * Make conmon-rs work with cargo 1.58
> 
> I played around with 1.58 and we could disable the tzdb feature, but this leads into a new issue:
> 
> ```
> error: package `time v0.3.14` cannot be built because it requires rustc 1.59.0 or newer, while the currently active rustc version is 1.58.1
> ```

ack, let me check on the other options and get back. Thanks!

**Comment by lsm5** [comment]
I'm building cargo 1.59 at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4805564/ after which I'll use it to bootstrap cargo 1.60 on that copr and then get conmon-rs built for epel repos. The rustc builds take a while, so this should complete sometime next week (hopefully).

**Comment by saschagrunert** [comment]
> I'm building cargo 1.59 at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4805564/ after which I'll use it to bootstrap cargo 1.60 on that copr and then get conmon-rs built for epel repos. The rustc builds take a while, so this should complete sometime next week (hopefully).

Cool, looks like it succeeded! Thank you so much!

**Comment by lsm5** [comment]
rust 1.60 building
epel9: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4809364/
epel8: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4809442/

once these are in place, i can go ahead with conmon-rs rebuild. I'll also try to keep rust for epel on copr in-sync with the stream versions going forward.

**Comment by lsm5** [comment]
mostly successful build at https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4811256/ 

@saschagrunert @haircommander is conmon-rs known to not work on i386? I can disable i386 for it in that case. Just that i686 is still one of the default fedora arches, so we might wanna ExclusiveArch it for official packaging.

**Comment by lsm5** [comment]
btw, I also wanna make sure everyone's aware before consuming this repo (especially coreos people). The podman-next copr also has other packages which are built from their respective upstream main branches. So, if coreos doesn't want the latest podman, crun etc., those should be excluded from the get go in their yum configs.

**Comment by saschagrunert** [comment]
> @saschagrunert @haircommander is conmon-rs known to not work on i386?

No I don't think so but I'm working on a fix in https://github.com/containers/conmon-rs/pull/688
