### ISSUE TITLE
Unable to re-attach after a successful attach

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#706]
### What happened?

We cannot reattach to a container because the attach path already exists:

```
FATA[0000] attaching running container failed: Internal error occurred: error attaching to container: create result: conmon-rs/common/proto/conmon.capnp:Conmon.attachContainer: create attach endpoint: Attach socket path already exists: /run/containers/storage/overlay-containers/1ac6dc4e679069ba32bfbd4307435da7551de15ad81e5fff6bc54757badafed1/userdata/2469c120ea14e5d8112e3886a514e1b86262841dac76a4011b008a0a79d55072/attach
```

### What did you expect to happen?

We should be able to re-attach containers.

### How can we reproduce it (as minimally and precisely as possible)?

Run a workload via CRI-O and crictl and try to attach twice.

### conmon-rs version

<details>
869e839
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by rphillips** [comment]
Does removing the following lines fix it?

https://github.com/containers/conmon-rs/blob/main/conmon-rs/server/src/attach.rs#L122-L124

**Comment by saschagrunert** [comment]
> Does removing the following lines fix it?
> 
> https://github.com/containers/conmon-rs/blob/main/conmon-rs/server/src/attach.rs#L122-L124

Already ongoing attach sessions would be overwritten in that case. Maybe we wanna move that handling completely to CRI-O?

**Comment by haircommander** [comment]
yeah I see we have two options:
- have the client reconnect to the same attach socket
- have the server create multiple attach instances
I think it should happen opaquely to the caller of the client to encapsulate as much logic in the client as possible

**Comment by saschagrunert** [comment]
How about:
- we reuse the attach socket for new connections
- automatically remove the socket if no more connections exist

**Comment by haircommander** [comment]
that sounds great!
