### ISSUE TITLE
Fedora 35 i686 build fails in copr

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#716]
### What happened?

The builds fails since a couple of commits with the error message: 

https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman-next/fedora-35-i386/04836395-conmon-rs/root.log.gz
```
DEBUG util.py:445:  No match for argument: golang-1.18.6-1.fc35.i386
DEBUG util.py:443:  Error: Unable to find a match: golang-1.18.6-1.fc35.i386
```

### What did you expect to happen?

The build should work like the other ones.

### How can we reproduce it (as minimally and precisely as possible)?

Mostly on every recent commit on https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/package/conmon-rs/

### conmon-rs version

<details>

```console
$ conmonrs --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>

**Comment by saschagrunert** [comment]
@lsm5 do you have any insights here? Do we have to bump the golang version?

**Comment by lsm5** [comment]
I'm hoping we don't have to care about i386 on f35. I disabled it few mins ago, but if you think we need it, I can look further into it.

**Comment by lsm5** [comment]
fwiw, many other packages also failed builds for f35 on i386, which is why I disabled them without actually looking into the failures.

**Comment by lsm5** [comment]
ah whoops, looks like it was the same dep causing issues. I added golang 1.18 separately in the buildroot and missed that for i386. Let me fix that. Since it's a trivial enough fix, I don't mind adding it.

**Comment by lsm5** [comment]
ugh the copr env is called `i386` but the rpms have `i686` in them. Fixed now and rebuilding ..

**Comment by saschagrunert** [comment]
All green now, thank you again for the fast help!
