### ISSUE TITLE
EPEL 8 package builds are failling

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#808]
A bunch of CentOS and epel 8 package builds are recently failing:
https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4944707/

The main error message seems to be:

```
Error: Unable to find a match: rust-1.61.0-1.el8.x86_64, golang-1.18.7-1.el8.x86_64
```

@lsm5 we can switch back to rust 1.58 if you don't mind. We already changed the repo to support that.

**Comment by lsm5** [comment]
fixed: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/build/4948394/

**Comment by saschagrunert** [comment]
Thank you so much @lsm5! :pray:
