### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon-rs#872]
We need a logo for conmon-rs to be easily identifiable compared to [conmon](https://github.com/containers/conmon).

**Comment by haircommander** [comment]
maybe we can get a slice of @mairin 's time :crossed_fingers:

**Comment by mairin** [comment]
Happy to help! Do you need one for conman and conman-rs both? Are there any existing assets? Would you like it to match the other containers org logos? (eg podman, cri-o, skopeo, buildah etc?)

**Comment by jwhonce** [comment]
Maybe a badge on a hat? Both skopeo and buildah include hats. Just a thought.

**Comment by saschagrunert** [comment]
Beside all other valid comments: We could also highlight the Rust bits by using a cute crab.

**Comment by haircommander** [comment]
for some reason I've always imagined conmon's logo being something like the all-seeing-eye haha

**Comment by mairin** [comment]
> for some reason I've always imagined conmon's logo being something like the all-seeing-eye haha

A crab with an all-seeing eye? :-)

**Comment by haircommander** [comment]
haha yeah sounds fun

**Comment by saschagrunert** [comment]
@mairin do you still think that you could support is with that?

**Comment by mairin** [comment]
@saschagrunert Yes definitely. I have a backlog between this icon and the updated youki logo. Do you have a specific deadline you're looking at having it available by? I can pull it higher in priority if needed.

**Comment by saschagrunert** [comment]
@mairin thank you for the update! There is no deadline for that, so it's up to you right now how to prioritize. :+1:

**Comment by jessicachitas** [comment]
Here is a work in progress version of the conmon logo that i've been working on. let me know your thoughts!

![image](https://user-images.githubusercontent.com/36636982/216132265-452ee3cb-48e4-462e-8c26-415b81217a15.png)

**Comment by jessicachitas** [comment]
going to be putting a the 7 sided shield around it as well once everyone is cool with it!

> Here is a work in progress version of the conmon logo that i've been working on. let me know your thoughts!
> 
> ![image](https://user-images.githubusercontent.com/36636982/216132265-452ee3cb-48e4-462e-8c26-415b81217a15.png)

**Comment by haircommander** [comment]
I think that's really cute! I find myself wondering how we can incorporate the fact it's a container monitor cleanly (it's possible there isn't a way, but I thought I would mention it)

also, I think the name at the bottom should be `conmon-rs` as `conmon` is written in C, and thus the crab wouldn't be as relevant

**Comment by saschagrunert** [comment]
It looks great! Having more details on it would probably clash with its simplicity.

Just an idea: We could make the eye more futuristic, for example like [Geordi La Forge](https://static.wikia.nocookie.net/memoryalpha/images/3/3f/Geordi_La_Forge%2C_2364.jpg/revision/latest/scale-to-width-down/700?cb=20180907022900&path-prefix=en) had it or [them from the Marvel comics](https://en.wikipedia.org/wiki/Cyclops_%28Marvel_Comics%29). This could be somehow seen as "looking through containers" or "seeing everything within containers".

**Comment by jessicachitas** [comment]
> It looks great! Having more details on it would probably clash with its simplicity.
> 
> _Just an idea:_ We could make the eye more futuristic, for example like [Geordi La Forge (Star Trek)](https://static.wikia.nocookie.net/memoryalpha/images/3/3f/Geordi_La_Forge%2C_2364.jpg/revision/latest/scale-to-width-down/700?cb=20180907022900&path-prefix=en) had it or [them from the Marvel comics](https://en.wikipedia.org/wiki/Cyclops_%28Marvel_Comics%29). This could be somehow seen as "looking through containers" or "seeing everything within containers".

Thanks for your idea! I really like the idea of the futuristic eye but to stick with the theme of all the other podman logos, I think it's best to stick with the eye that is on it already but solid ideas!

**Comment by jessicachitas** [comment]
![conmon-v3](https://user-images.githubusercontent.com/36636982/220142216-b6c0cd51-0b5e-4e0c-a57e-e2e835e4193d.png)

Added the rs and gave more dimension to the eye by adding an outline, found that the blue and orange side by side was messing with my eyes a bit so wanted to create that separation

**Comment by saschagrunert** [comment]
@jessicachitas I love it!

**Comment by jessicachitas** [comment]
> @jessicachitas I love it!

The shine on its eye as well kinda makes it look like the lens of a camera! Just seeing that now haha

**Comment by jessicachitas** [comment]
I think the next step is to integrate it into the shield shape with seven sides. I have an idea of having the crab sitting on a beach or something like that for it? What do you think? Unless you would like to keep it simple like the podman one, I can do that as well!

**Comment by saschagrunert** [comment]
Hm, yeah I’d personally prefer simplicity, but @haircommander ans @rphillipsay have different thoughts.

**Comment by haircommander** [comment]
I agree with simple!

**Comment by haircommander** [comment]
looks great @jessicachitas thank you!

**Comment by rphillips** [comment]
This is awesome. Thank you!

**Comment by cgwalters** [comment]
On Wed, Feb 1, 2023, at 2:31 PM, Peter Hunt wrote:
> I think that's really cute! I find myself wondering how we can 
> incorporate the fact it's a container monitor cleanly (it's possible 
> there isn't a way, but I thought I would mention it)
>
> also, I think the name at the bottom should be `conmon-rs` as `conmon` 
> is written in C, and thus the crab wouldn't be as relevant

But is the fact that conmon-rs is written in Rust really relevant either?  As a container user I want to hear things like my infrastructure is more efficient or has more features.  

Personally I think common-rs should just *replace* conmon in the future (like at a package level).  

I would think of it more like “conmon 2.0” or so.

Related to this a bit, while Rust is in some domains still seen as novel, I think it is well on its way to become *the default*.  When that happens we’re not going to use the crab logo and suffix everything with -rs anymore than current conmon should have been conmon-c.

So combining these I’d suggest de-emphasizing the crab.  Maybe a stack of containers being watched by a camera or eye, with a crab logo on the side of the camera?  Dunno.

Any thoughts on just planning to merge this project and take over the name “conmon”?  (No -rs)

**Comment by baude** [comment]
well said @cgwalters i would agree with what you've said.

**Comment by mairin** [comment]
@jessicachitas and I thought the crab would be fine in any case since the container logos have a general sea/ocean kind of theme... it's less cute sea creature but how would you feel about a periscope popping out of the water?

**Comment by jessicachitas** [comment]
![conmon-in-shield-v1](https://user-images.githubusercontent.com/36636982/224819029-76dea868-5db3-454a-b6e1-8797cd4ee31e.png)

Here is the conmon-rs crab with the shield, if you would like me to experiment with the ideas that @cgwalters and @mairin suggested, I am more than happy to develop them further.

**Comment by saschagrunert** [comment]
I really like the version of @jessicachitas now! :)

**Comment by saschagrunert** [comment]
@haircommander @rphillips thoughts on the above?

**Comment by haircommander** [comment]
I like it! The concerns about involvement of the crab are valid, and would entertain other designs, but I personally would be happy with this one.

**Comment by saschagrunert** [comment]
@jessicachitas I'm personally happy with the logo. Do you provide a SVG side by side to a higher resolution PNG?

**Comment by mrunalp** [comment]
This is great. Thanks @jessicachitas !

**Comment by saschagrunert** [comment]
Closing now, thank you again @jessicachitas!

**Comment by jessicachitas** [comment]
![conmon](https://user-images.githubusercontent.com/36636982/227322892-905c7353-dac7-477d-b451-6e05f5a66153.svg)
![conmon-in-shield-final](https://user-images.githubusercontent.com/36636982/227322896-401186ff-25bf-4ff6-a93c-593d33f12ee5.png)
![conmon-final](https://user-images.githubusercontent.com/36636982/227322898-80c22f65-89de-487b-9908-95e16e317a02.png)
